export const SORT_CRITERIA_CHANGE = 'SORT_CRITERIA_CHANGE';

export const SEARCH_CRITERIA_CHANGE = 'SEARCH_CRITERIA_CHANGE';
export const SEARCH_STRING_CHANGE = 'SEARCH_STRING_CHANGE';

export const FETCH_DATA_BEGIN = 'FETCH_DATA_BEGIN';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
